"""Domain types for M6a's email surface (EmailPort).

Plain, stdlib-only dataclasses, matching ``PageHandle``'s own
"explicit, typed fields, not one opaque blob" precedent
(``docs/architecture/m6a-communications.md``). ``received_at`` is a
plain ``str`` (the real server-reported timestamp), not a domain
``datetime`` requiring ``ClockPort`` -- the value is authoritative
from the remote IMAP server, not generated by JARVIS itself, the same
reasoning ``PageHandle``'s own fields are plain adapter-reported
values, not JARVIS-generated ones.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class EmailSummary:
    """One message's own real headers, without its full body."""

    message_id: str
    sender: str
    subject: str
    received_at: str


@dataclass(frozen=True)
class EmailMessage:
    """One real message's full, real content."""

    message_id: str
    sender: str
    recipients: tuple[str, ...]
    subject: str
    body: str
    received_at: str
